# Generated by Django 6.0.8 on 2026-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0013_alter_billingrcmjob_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRemovalJob',
            fields=[
                ('job_id', models.CharField(db_column='job_id', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('sm_device_id', models.CharField(db_column='sm_device_id', max_length=100)),
                ('consumer_id', models.CharField(db_column='consumer_id', max_length=100)),
                ('service_point_id', models.CharField(db_column='service_point_id', max_length=100, null=True)),
                ('job_created_at', models.DateTimeField(auto_now_add=True, db_column='job_created_at')),
                ('job_run_at', models.DateTimeField(auto_now=True, db_column='job_run_at')),
                ('payload', models.JSONField(db_column='payload')),
                ('job_status', models.CharField(choices=[('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_column='job_status', max_length=100)),
                ('job_message', models.TextField(db_column='job_message')),
                ('retries', models.IntegerField(db_column='retries', default=1, help_text='Number of times the job has been retried')),
            ],
            options={
                'db_table': 'meter_removal_jobs',
                'ordering': ['-job_created_at'],
                'indexes': [models.Index(fields=['job_id'], name='meter_removal_jobs_job_id_idx')],
            },
        ),
    ]
